version: 0.1
phases:
  install:
    commands:
      - npm install --silent --save-dev -g \
                babel \
                babel-cli \
                gulp-babel \
                gulp-cli \
                bower \
                typescript \
                typings \
                webpack \
                serverless \
                ts-loader \
                json-loader \
                ts-node \
                serverless-webpack \
                tslint \
                tslint-config-olo \
                mocha \
                chai \
                karma \
                karma-typescript-preprocessor2 \
                karma-webpack \
                karma-chai \
                karma-mocha \
                phantomjs \
                phantomjs-prebuilt \
                karma-phantomjs-launcher \
                request \
                aws-sdk \
                aws-lambda \
                uuid
      - npm install --save -g @types/aws-sdk
      - npm install --save -g @types/aws-lambda
      - npm install --save -g @types/core-js
      - rm node_modules
      - ln -s /usr/local/lib/node_modules node_modules
      - typings i --save dt~mocha --global
      - typings i --save chai
  pre_build:
    commands:
      - npm run test:local
  build:
    commands:
      - npm run deploy:cicd
  post_build:
    commands:
      - npm run test:remote