service: serverless-typescript-demo

provider:
  name: aws
  runtime: nodejs4.3
  profile: TEKsystems
  region: us-west-2
  iamRoleStatements:
      - Effect: "Allow"
        Resource: "*"
        Action:
          - "kinesis:*"
  environment:
      KINESIS_STREAM: ${opt:stage, self:provider.stage}-data-receiver

plugins:
  - serverless-webpack

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: hello
         method: get

  dataReceiver:
    handler: handler.dataReceiver

  logger:
    handler: handler.logger
    events:
      - stream: arn:aws:kinesis:us-west-2:${env:ACCOUNT_ID}:stream/${self:provider.environment.KINESIS_STREAM}