service: serverless-typescript-demo

provider:
  name: aws
  runtime: nodejs4.3
  profile: TEKsystems
  region: us-west-2
  iamRoleStatements:
      - Effect: "Allow"
        Resource: "*"
        Action:
          - "kinesis:*"
  environment:
      KINESIS_STREAM: ${opt:stage, self:provider.stage}-data-receiver

plugins:
  - serverless-webpack

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: hello
         method: get

  dataReceiver:
    handler: handler.dataReceiver

  logger:
    handler: handler.logger
    events:
      - stream:
        type: kinesis
        arn:
          Fn::GetAtt:
            - ResourcesKinesisStream
            - Arn
        batchSize: 1

resources:
  Resources:
    ResourcesKinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:provider.environment.KINESIS_STREAM}
        ShardCount: 1

